version: '3.8'

services:
  app:
    build: .
    command: yarn run dev
    volumes:
      - ./src:/src:cached
      - node_modules:/node_modules
    working_dir: "/src"
    ports:
      - "3000:3000"
      - 24678:24678
    tty: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: